"""
Low-Volatility Strategy v1 - Validation Baseline
"""

STRATEGY_VERSION = "1.0"
STRATEGY_NAME = "LOW_VOL_60D"

# Execution
HOLDING_PERIOD = 21
REBALANCE_FREQ = 1
REBALANCE_MODE = "month_end"
EXECUTION_DELAY = 1
TRANSACTION_COST = 0.0020
EXECUTION_USE_TRADING_DAYS = True
ENABLE_DYNAMIC_COST = True
TRADE_SIZE_USD = 10000

# Universe
MIN_MARKET_CAP = 500e6
MIN_DOLLAR_VOLUME = 1e6
MIN_PRICE = 5.0

# Backtest periods
TRAIN_START = "2010-01-04"
TRAIN_END   = "2017-12-31"
TEST_START  = "2018-01-01"
TEST_END    = "2026-01-28"

# Price data selection
USE_ADJ_PRICES = True

# Calendar symbol for rebalance calendar (optional)
CALENDAR_SYMBOL = "SPY"

# Low-vol tuning
LOW_VOL_WINDOW = 120
LOW_VOL_LOG_RETURN = True
LOW_VOL_USE_RESIDUAL = True
LOW_VOL_BENCH_SYMBOL = "SPY"
LOW_VOL_DOWNSIDE_ONLY = True

# Stage 1 baseline (winsor + rank)
SIGNAL_ZSCORE = False
SIGNAL_RANK = True
SIGNAL_RANK_PCT = True
SIGNAL_WINSOR_PCT_LOW = 0.01
SIGNAL_WINSOR_PCT_HIGH = 0.99
INDUSTRY_NEUTRAL = False
INDUSTRY_MIN_GROUP = 3
INDUSTRY_COL = "industry"
INDUSTRY_MAP_PATH = "../data/company_profiles.csv"
SIGNAL_SMOOTH_WINDOW = None
SIGNAL_SMOOTH_METHOD = "sma"

# Optional risk neutralization (institutional mode)
SIGNAL_NEUTRALIZE_SIZE = False
SIGNAL_NEUTRALIZE_BETA = False
SIGNAL_NEUTRALIZE_COLS = None

# Beta settings (used if SIGNAL_NEUTRALIZE_BETA = True)
BETA_LOOKBACK = 252
BETA_BENCH_SYMBOL = "SPY"
BETA_USE_LOG_RETURN = True
