"""
Quality Strategy v2 - Mainstream Baseline Configuration
"""

STRATEGY_VERSION = "2.1"
STRATEGY_NAME = "QUALITY_MAINSTREAM_COMPOSITE"

# Factor (LOCKED)
QUALITY_WEIGHTS = {
    "roe": 1.0,
    "roa": 0.5,
    "gross_margin": 0.5,
    "cfo_to_assets": 1.0,
    "debt_to_equity": -0.5,
}
QUALITY_MAINSTREAM_COMPOSITE = True
QUALITY_COMPONENT_TRANSFORM = "identity"
QUALITY_COMPONENT_INDUSTRY_ZSCORE = True
QUALITY_COMPONENT_WINSOR_PCT_LOW = 0.01
QUALITY_COMPONENT_WINSOR_PCT_HIGH = 0.99
QUALITY_COMPONENT_MIN_COUNT = 3
QUALITY_COMPONENT_MISSING_POLICY = "drop"

# Fundamentals cache location
FUNDAMENTALS_DIR = "../data/fmp/ratios/quality"

# Execution (LOCKED)
HOLDING_PERIOD = 20
REBALANCE_FREQ = 21
EXECUTION_DELAY = 1
TRANSACTION_COST = 0.0020
EXECUTION_USE_TRADING_DAYS = True
ENABLE_DYNAMIC_COST = True
TRADE_SIZE_USD = 10000

# Universe (LOCKED)
MIN_MARKET_CAP = 500e6
MIN_DOLLAR_VOLUME = 1e6
MIN_PRICE = 5.0

# Backtest periods (LOCKED)
TRAIN_START = "2010-01-04"
TRAIN_END   = "2017-12-31"
TEST_START  = "2018-01-01"
TEST_END    = "2026-01-28"

# Price data selection
USE_ADJ_PRICES = True

# Calendar symbol for rebalance calendar (optional)
CALENDAR_SYMBOL = "SPY"

# Stage 1 baseline (winsor + rank)
SIGNAL_ZSCORE = False
SIGNAL_RANK = True
SIGNAL_WINSOR_PCT_LOW = 0.01
SIGNAL_WINSOR_PCT_HIGH = 0.99
INDUSTRY_NEUTRAL = False
INDUSTRY_MIN_GROUP = 3
INDUSTRY_COL = "industry"
INDUSTRY_MAP_PATH = "../data/company_profiles.csv"
SIGNAL_SMOOTH_WINDOW = None
SIGNAL_SMOOTH_METHOD = "sma"

# Optional risk neutralization (institutional mode)
SIGNAL_NEUTRALIZE_SIZE = False
SIGNAL_NEUTRALIZE_BETA = False
SIGNAL_NEUTRALIZE_COLS = None

# Beta settings (used if SIGNAL_NEUTRALIZE_BETA = True)
BETA_LOOKBACK = 252
BETA_BENCH_SYMBOL = "SPY"
BETA_USE_LOG_RETURN = True
